import type { Metadata } from "next";
import "./globals.css";
import { Providers } from "@/lib/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className="bg-gradient-to-b from-blue-400 via-blue-500 to-blue-700 bg-no-repeat h-screen">{children}</body>
      </html>
    </Providers>
  );
}
